name: Release
on: workflow_dispatch
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - name: Bump
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  npm ci
                  npx standard-version
                  git push --follow-tags origin main
            - name: Publish
              run: |
                  npm run build
                  npm publish dist/libs/sherlock --access public
                  npm publish dist/libs/sherlock-proxy --access public
                  npm publish dist/libs/sherlock-rxjs --access public
                  npm publish dist/libs/sherlock-utils --access public
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
